<?php
echo $this->doctype('HTML5');
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
//$this->headTitle('Sistema Administrativo');

?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
	<head>
		<?php echo $this->headMeta(); ?>
	    <meta name="description" content="">
	    <meta name="author" content="scumbagblues">
		<?php echo $this->headTitle(); ?>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<?php echo $this->jQuery();?>
		<?php echo $this->headScript()->prependFile($this->baseUrl() . "/js/bootbox.js")
									   ->prependFile($this->baseUrl() . "/js/funciones.js")
									   ->prependFile($this->baseUrl() . "/js/bootstrap2/bootstrap.js");?>
		<link type="text/css" rel="stylesheet"
			href="<?php echo $this->baseUrl() . '/css/bootstrap2/bootstrap.min.css'?>" />
		<link type="text/css" rel="stylesheet"
			href="<?php echo $this->baseUrl() . '/css/bootstrap2/bootstrap-responsive.min.css'?>" />
		<link type="text/css" rel="stylesheet" href="<?php echo  $this->baseUrl().'/css/jquery-ui.css'?>" />
		<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
	    <!--[if lt IE 9]>
	      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	    <![endif]-->
	</head>
	<body>

		<div class="navbar navbar-inverse navbar-fixed-top">
	      <div class="navbar-inner">
	        <div class="container">
	          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	          </a>
	          <a class="brand" href="#">Project name</a>
	          <div class="nav-collapse collapse">
	            <ul class="nav">
	              <li class="active"><a href="#"><?php echo $this->translate('Home');?></a></li>
	              <li><a href="#about">About</a></li>
	              <li><a href="#contact"><?php echo $this->translate('Contact');?></a></li>
	              <li class="dropdown">
	                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
	                <ul class="dropdown-menu">
	                  <li><a href="#">Action</a></li>
	                  <li><a href="#">Another action</a></li>
	                  <li><a href="#">Something else here</a></li>
	                  <li class="divider"></li>
	                  <li class="nav-header">Nav header</li>
	                  <li><a href="#">Separated link</a></li>
	                  <li><a href="#">One more separated link</a></li>
	                </ul>
	              </li>
	            </ul>
	          </div><!--/.nav-collapse -->
	        </div>
	      </div>
	    </div>

	<div class="container">
		  <!-- Main hero unit for a primary marketing message or call to action -->
	      <div class="hero-unit">
	      	<?php echo $this->layout()->content; ?>
	      </div>
	
	      <!-- Example row of columns -->
	      <div class="row">
	        <div class="span4">
	          <h2>Heading</h2>
	          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
	          <p><a class="btn" href="#">View details &raquo;</a></p>
	        </div>
	        <div class="span4">
	          <h2>Heading</h2>
	          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
	          <p><a class="btn" href="#">View details &raquo;</a></p>
	       </div>
	        <div class="span4">
	          <h2>Heading</h2>
	          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
	          <p><a class="btn" href="#">View details &raquo;</a></p>
	        </div>
	      </div>
	
	      <hr>
	
	      <footer>
	        <p>&copy; Company 2012</p>
	      </footer>
	</div> <!-- /container -->
   </body>
 </html>  